### PR TITLE
Chapter2 draft1

### PR DESCRIPTION
**Pull request by yardasol**
This PR contains the 1st draft for chapter 2 of my Master's thesis.

#### Writing checklist
- [x] Run a spell checker.
- [x] The Oxford comma must appear in lists ("lions, tigers, and bears.")
- [x] Do not use the word "where" unless referring to a location (try "such that" or "in which").
- [x] Do not use the word "when" unless referring to a time (try "if" instead).
- [x] Only use "large" when referring to size.
- [x] Use of "very" suggests that a cooler word exists.
- [x] Other misused/overused words include: code, input, output, different, value, amount, model.
- [x] Articles such as "a" "the" "some" "any" and "each" must appear where necessary.
- [ ] All subjects match the plurality of their verbs ( no: "Apples is tasty" yes: "Apples are tasty").
- [ ] Avoid run-on sentences.
- [ ] Clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [ ] Reduce vague words (important, methodologic).
- [ ] Reduce acronyms / jargon
- [x] Expand all acronyms on first use (rely on the acros.tex file and glossaries package to automate this).
- [ ] Get rid of unnecessary prepositional phrases -- author clearing throat (It can be shown that)
- [ ] Get rid of extraneous adverbs (very, really, quite, basically, generally)
- [ ] Get rid of there are / there is
- [ ] Turn negatives to positives (she was not often right -> she was usually wrong).
- [ ] Get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [ ] Get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [ ] Use strong verbs (use sparingly: is, are, was, were, be, been, am).
- [ ] Avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes").
- [ ] Don't bury the verb (keep the predicate close to the subject at the beginning of the sentence).
- [ ] Data is plural (the data are critical).
- [ ] Compare to (point out similarities between different things) vs.  compared with (point out differences between similar things)
- [ ] Punctuation helps you to vary your sentence structure.
- [ ] Power to separate in increasing power: comma, colon, dash, parentheses, semicolon, period
- [ ] In increasing order of formality: dash, parentheses, all of the others. Don't overdo it with the dash and parentheses
- [ ] Semicolon: connects two independent clauses. OR separates items when the list contain internal punctuation.
- [ ] Use a colon to introduce a list, quote, explanation, conclusion, or amplification.
- [ ] If there's a list in a sentence, it shouldn't come before the colon.
- [ ] Use a dash to insert something in the middle of the sentence. Don't overuse it.
- [ ] Always use isotopic notation like `$^{239}Pu$`. Never `$Pu-239$` or `$plutonium-239$`.
- [ ] Elemental symbols (Ni, Li, Na, Pu) are capitalized, but their names are not (nickel, lithium, sodium, plutonium).
- [ ] A phrase of the form <verb>ion of <noun> is probably clearer as <noun> <verb>ion. (For example, convert "calculation of velocity" to "velocity calculation".)
- [ ] Cite all images, methods, software, and empirical data. Review [the principles](https://www.force11.org/software-citation-principles) and try [CiteAs](https://citeas.org/about) if necessary.
- [ ] Refer to software consistently by name.
- [ ] Each sentence/paragraph should logically follow the previous sentence/paragraph.
- [ ] Be concise and direct.
- [ ] When giving examples, use variables instead of numbers and use symbolic math instead of acronyms.
- [ ] When you introduce words or phrases that are unusual or likely to be unfamiliar to the reader, italicize them.
- [ ] If you use an uncommon word, either consider changing it or define it in its first usage.
- [ ] You're a human writing for other humans: Make the wording exciting, and remember some people reading it won't know as much jargon as you do.
- [ ] Vary your sentence structure to keep readers engaged.

### CODE REVIEW

**Comment by yardasol** [comment]
pdf 
https://github.com/arfc/2022-yardas-ms/pull/4/files#diff-3b1eb1b88621929a670fcc2914aa731fe92c6196ac726d9bc2b13e5c32c69582

**Comment by yardasol** [comment]
pdf 
[main.pdf](https://github.com/arfc/2022-yardas-ms/files/9668685/main.pdf)

**Comment by yardasol** [comment]
@hwacc-y Can you review the most recently posted PDF?

**Comment by hwacc-y** [comment]
@yardasol Yes, I will start reviewing. Sorry I missed the tag.

**Pull request merged**
